# Generated by Django 3.2.9 on 2022-03-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_alter_playlist_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='videos',
        ),
    ]
