# Generated by Django 3.2.9 on 2022-03-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0011_alter_playlist_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProxy',
            fields=[
            ],
            options={
                'verbose_name': 'TV Show',
                'verbose_name_plural': 'TV Shows',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('playlists.playlist',),
        ),
    ]
