# Generated by Django 3.2.9 on 2022-03-12 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0012_movieproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieproxy',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
    ]
